### ISSUE TITLE
Drivers needed for Notepad++

### ISSUE THREAD

**Issue by Carolynjp** [MarkHoeber/get_started_html#5]
Hi Everyone,

In reading the HTML assignment I find I need Notepad installed.  I always thought this was automatically included but I'm not finding it on my PC.  Does it seem right I may need to update my drivers?  A company called Slimline is trying to charge me to update my drivers.  Does this seem legit?  My PC is an HP with Windows 10.   Thoughts? 

Thanks,
Carolyn

**Comment by MarkHoeber** [comment]
@Carolynjp  I don't know windows, but this doesn't sound legit to me.  You shouldn't have to pay for a text editor.  You can try installing Sublime Text to Atom for free.

**Comment by Carolynjp** [comment]
Thanks!  I worked with it a while and got Notepad up and followed the HTML assignment (Video) and had success with the example.  I wrote it in Notepad, saved it an opened it in Firefox. It would not open in Chrome or Edge.  So, fooling with that a bit.  I will work on the webpage assignment now that it's all good. 
Thank you,
Carolyn
